# 注意: このファイルは、直接Includeしないでください。

# サーバ情報
Define PGMFILS "D:/ProgramFiles"
Define SRVROOT "${PGMFILS}/apache/2_4_54"
Define PORT "180"
Define PGMSRC "D:/ProgramSource"
Define SERVER_ADMIN "your@example.com"
ServerRoot "${SRVROOT}"
ServerSignature off
ServerTokens ProductOnly

# ログ情報
ErrorLog "logs/error.log"
LogLevel warn
LogFormat "\"%h\", \"%{%Y/%m/%d %T}t.%{usec_frac}t\", \"%r\", \"%>s\", \"%b\", \"%{HTTPS}e\", \"%{User-agent}i\", \"%{Accept-Language}i\", \"%{Referer}i\"" common

# モジュール
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule dir_module modules/mod_dir.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule alias_module modules/mod_alias.so
LoadModule headers_module modules/mod_headers.so
LoadModule mime_module modules/mod_mime.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule http2_module modules/mod_http2.so
LoadModule deflate_module modules/mod_deflate.so
LoadModule filter_module modules/mod_filter.so

# PHP
LoadModule php_module "${PGMFILS}/php/8_3_0/php8apache2_4.dll"
PHPIniDir "${PGMFILS}/php/8_3_0"

# gzip圧縮を有効化
DeflateCompressionLevel 1

# アクセス禁止
<Directory />
    AllowOverride none
    Require all denied
</Directory>

# ダミー
Define VSRVROOT "${SRVROOT}"
<VirtualHost *:*>
    ServerName any
    DocumentRoot "${VSRVROOT}/htdocs"
    <Directory "${VSRVROOT}/htdocs">
        Require all granted
        DirectoryIndex index.html
    </Directory>
</VirtualHost>

# 共通ポート
Listen ${PORT}

# PHPWebLibrary
Define VSRVROOT "${PGMSRC}/PhpWebLibrary"
# 各自PCのhostsに登録したホスト名を指定してください
<VirtualHost (各自のホスト名):${PORT}>
    Protocols h2 http/1.1
    Include "${VSRVROOT}/conf/vhost.conf"
</VirtualHost>

# アクセス禁止(特殊ファイル)
<Files "\.ht*">
    Require all denied
</Files>
