ServerAdmin ${SERVER_ADMIN}
DocumentRoot "${VSRVROOT}/www/html"
ErrorLog "${VSRVROOT}/logs/error.log"
CustomLog "${VSRVROOT}/logs/access.log" common
<Directory "${VSRVROOT}/www/html">
    AllowOverride Options
    Require all granted
    DirectoryIndex index.html Main.php
</Directory>
Alias "/favicon.ico" "${VSRVROOT}/www/html/img/icon/favicon.ico"
Alias "/docs" "${VSRVROOT}/docs"
<Directory "${VSRVROOT}/docs">
    Require all granted
</Directory>
Alias "/testPrograms" "${VSRVROOT}/www/testPrograms"
<Directory "${VSRVROOT}/www/testPrograms">
    Require all granted
</Directory>

# キャッシュをEtagチェックさせる
<FilesMatch "\.(html?|php)$">
    Header set Cache-Control "private, no-cache, proxy-revalidate, no-transform"
</FilesMatch>
<FilesMatch "\.(css|js|ico|md)$">
    Header set Cache-Control "no-cache"
</FilesMatch>
<FilesMatch "\.(jpe?g|gif|png|svg)$">
    Header set Cache-Control "no-cache"
</FilesMatch>

# gzip圧縮(対応ブラウザのみ)
<IfModule deflate_module>
    <IfModule filter_module>
        RequestHeader edit If-None-Match '^"(.*)-(gzip|br)"$' '"$1", "$2"'
        AddOutputFilterByType DEFLATE text/html
        AddOutputFilterByType DEFLATE text/plain
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE application/json
    </IfModule>
</IfModule>

# PHPの拡張子を登録
AddHandler application/x-httpd-php .php

# Markdown
AddType "text/plain; charset=utf-8" .md

# PHPライブラリ
php_value include_path ".;${VSRVROOT}/www/libs/php"

# cURLに必要
LoadFile "${VSRVROOT}/php/libssh2.dll"

# XDebug 3
php_value xdebug.log "${VSRVROOT}/logs/xdebug.log"
