[PHP]

; --------------------------------------------------------------------------------------------------
; 環境(開発環境用)
; --------------------------------------------------------------------------------------------------
; エラー
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On

; サーバ処理上限
max_execution_time = 30
max_input_time = 60
memory_limit = 128M
output_buffering = 4096

; セッション制御
session.name = WEBSESSIONID
session.use_strict_mode = 1
session.gc_divisor = 1000
session.sid_bits_per_character = 5

; データ制御
variables_order = "GPCS"
request_order = "GP"
register_argc_argv = Off

; ヘッダ制御
expose_php = Off

; 省略
short_open_tag = Off

; 例外
zend.exception_ignore_args = Off
zend.exception_string_param_max_len = 15
; --------------------------------------------------------------------------------------------------
; モジュール
; --------------------------------------------------------------------------------------------------
; 拡張モジュールのディレクトリ
extension_dir = "ext"

; 拡張モジュール
;extension = bz2
extension = curl
;extension = ffi
;extension = ftp
;extension = fileinfo
;extension = gd
;extension = gettext
;extension = gmp
;extension = intl
;extension = imap
;extension = ldap
extension = mbstring
;extension = exif      ; Must be after mbstring as it depends on it
;extension = mysqli
;extension = oci8_12c  ; Use with Oracle Database 12c Instant Client
;extension = oci8_19  ; Use with Oracle Database 19 Instant Client
;extension = odbc
;extension = openssl
;extension = pdo_firebird
extension = pdo_mysql
;extension = pdo_oci
;extension = pdo_odbc
extension = php_sqlsrv_83_ts_x64.dll
extension = php_pdo_sqlsrv_83_ts_x64.dll
;extension = pdo_pgsql
;extension = pdo_sqlite
;extension = pgsql
;extension = shmop
;extension = snmp
;extension = soap
;extension = sockets
;extension = sodium
;extension = sqlite3
;extension = tidy
;extension = xsl
;extension = zip

;zend_extension = opcache
;zend_extension = php_xdebug-3.3.1-8.3-vs16-x86_64.dll

; モジュール設定
[cURL]
curl.cainfo = {CACERT_PATH}

[Date]
date.timezone = Asia/Tokyo

[mbstring]
mbstring.language = Japanese

[Xdebug 3]
xdebug.mode = develop,debug
xdebug.start_with_request = trigger
